### ISSUE TITLE
Create Prometheus addon 

### ISSUE THREAD

**Issue by zpatrick** [quintilesims/kubernetes-addons#6]
Create an addon that installs and configures [Prometheus](https://prometheus.io/) for EKS clusters. 
This addon should include the necessary role bindings and other .yaml files in the repo, and be installed via a single `make install` command.

**Comment by sesh-kebab** [comment]
I think a helm chart, installable as a package rather than a make file would be better. We could then take this and include it in our production cluster tf with a single line.
